name: blog-app-dev
services:
  api:
    depends_on:
      db:
        condition: service_healthy
    image: api-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: development
      JWT_SECRET: secret
      SESSION_SECRET: secret
      DATABASE_URL: postgres://the_user:the_password@db:5432/the_database
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: blog-app-dev-api
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: the_user
      POSTGRES_PASSWORD: the_password
      POSTGRES_DB: the_database
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'the_user', '-d', 'the_database']
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: blog-app-dev-db
  reverse-proxy:
    depends_on:
      - api
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 5050:80
    container_name: pg_admin
    depends_on:
      - db
volumes:
  db-data:
